language: node_js
node_js:
  - 10
  - 9
  - 8

stages:
  - name: Run Tests
    if: NOT branch = master
  - name: Run Tests and Send Coverage
    if: branch = master

jobs:
  include:
    - stage: Run Tests
      install:
      - npm install
      script:
      - echo "Running Tests"
      - npm run test

    - stage: Run Tests and Send Coverage
      install:
        - npm install
      script:
        - echo "Running Tests"
        - npm run coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
