sudo:
  required
dist:
  trusty
language:
  node_js
install:
  - npm install -g codecov
node_js:
  - "8"
  - "9"
  - "10"
stages:
  - name: test
        # require the branch name to be master (note for PRs this is the base branch name)
    script:
      - npm run test
  - name: coverage
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
    script:
      - npm run coverage
      - codecov
